export const IPC_CHANNELS = {
  FILE: {
    READ: 'file:read',
    WRITE: 'file:write',
    DELETE: 'file:delete',
    CREATE_DIR: 'file:create-dir',
    LIST_DIR: 'file:list-dir',
    SELECT_FOLDER: 'file:select-folder',
    SELECT_FILE: 'file:select-file',
    SEARCH: 'file:search',
  },
  TERMINAL: {
    CREATE: 'terminal:create',
    INPUT: 'terminal:input',
    RESIZE: 'terminal:resize',
    KILL: 'terminal:kill',
    ON_DATA: 'terminal:on-data',
    ON_EXIT: 'terminal:on-exit',
  },
  GIT: {
    INIT: 'git:init',
    STATUS: 'git:status',
    STAGE: 'git:stage',
    UNSTAGE: 'git:unstage',
    COMMIT: 'git:commit',
    PUSH: 'git:push',
    PULL: 'git:pull',
    FETCH: 'git:fetch',
    BRANCHES: 'git:branches',
    CHECKOUT: 'git:checkout',
    CREATE_BRANCH: 'git:create-branch',
    DELETE_BRANCH: 'git:delete-branch',
    DIFF: 'git:diff',
    LOG: 'git:log',
    MERGE: 'git:merge',
  },
  DEBUG: {
    START: 'debug:start',
    STOP: 'debug:stop',
    SET_BREAKPOINTS: 'debug:set-breakpoints',
    PAUSE: 'debug:pause',
    CONTINUE: 'debug:continue',
    STEP_OVER: 'debug:step-over',
    STEP_INTO: 'debug:step-into',
    STEP_OUT: 'debug:step-out',
    EVALUATE: 'debug:evaluate',
    VARIABLES: 'debug:variables',
    ON_EVENT: 'debug:on-event',
  },
  PLUGIN: {
    GET_INSTALLED: 'plugin:get-installed',
    INSTALL: 'plugin:install',
    UNINSTALL: 'plugin:uninstall',
    ENABLE: 'plugin:enable',
    DISABLE: 'plugin:disable',
    EXECUTE_COMMAND: 'plugin:execute-command',
  },
  AI: {
    CHAT: 'ai:chat',
    COMPLETE: 'ai:complete',
    EXPLAIN: 'ai:explain',
    FIX_ERRORS: 'ai:fix-errors',
    REFACTOR: 'ai:refactor',
  },
  SETTINGS: {
    READ: 'settings:read',
    WRITE: 'settings:write',
  },
} as const;
