name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: "--win"
          - os: ubuntu-latest
            target: "--linux"
          - os: macos-latest
            target: "--mac"

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install
      - name: Build & Package Binary Installer (${{ matrix.target }})
        run: node scripts/package.js ${{ matrix.target }}
      - name: Upload Binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.exe
            release/*.AppImage
            release/*.dmg
            release/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
